### ISSUE TITLE
an issue with `shape = "ellipse"`

### ISSUE THREAD

**Issue by Syutenjyo** [hughjonesd/ggmagnify#10]
when i draw an ellipse annotation in geom_magnify, it just worked wrong
```R
ggplot(diamonds[diamonds$carat>1.2,], aes(carat, depth, color = cut)) + 
  geom_point() + 
  geom_magnify(from=c(1.8,63,2.2,67),to=c(3.6,48,6,58),shadow = T,shape = "ellipse") +
  coord_cartesian(clip = "off") + 
  theme(legend.position = c(1.15,.75),plot.margin = margin(20,90,10,10))
```
![image](https://user-images.githubusercontent.com/69134968/235985017-0f5a7f21-ea68-4d2e-bbd7-3ccc13d62690.png)
the annotation still looks like a rectangle thogth circled in an ellipse ┗( T﹏T )┛

**Comment by hughjonesd** [comment]
You need to use a device which supports masks, also R 4.2 or higher.

**Comment by Syutenjyo** [comment]
thanks, when i export as a pdf file, the ellipse annotation works.
