### ISSUE TITLE
Fill area between lines of magnified inset

### ISSUE THREAD

**Issue by etiennebacher** [hughjonesd/ggmagnify#17]
Hi, this is a very nice package! It would be cool if it was possible to fill the area between the lines so that we can get the red area like below:

![image](https://github.com/hughjonesd/ggmagnify/assets/52219252/fb4a29ee-4ab3-4e30-9001-f3d4565865db)

Here's the code I have so far (coming from [this SO answer](https://stackoverflow.com/questions/74135487)):

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is TRUE
library(rnaturalearth)
library(ggmagnify)

europe <- ne_countries(continent = "Europe", scale = 'medium',
                       type = 'map_units', returnclass = 'sf') 

your_map <- ggplot(europe) +
  geom_sf() +
  xlim(c(-20, 50)) +
  ylim(c(35, 70)) +
  theme_linedraw()

ggm <- your_map + 
  geom_magnify(
    from = c(9, 15, 42, 45),
    to = c(22, 36, 46, 52),
    colour = "red",
    linewidth = 1
  ) 

ggm
```

![](https://i.imgur.com/OT1pde2.png)

---

Add a 👍 on this post to show support for this feature.

**Comment by hughjonesd** [comment]
I like it but I think it will be complex. In particular, it's easy to draw the magnified inset over the shaded area. But the target area isn't redrawn. So you have to draw an irregular shaded shape, between the two projection lines and not including the target area. (Which can be elliptical or even an arbitrary shape...!)

Sorry, but I think this is best done with a manual tool. I'll leave this request open though, and if enough people vote for it I will reconsider.

**Comment by hughjonesd** [comment]
OK, this got some votes. It's now enabled in the `experiment-shaded-projection` branch, if you want to try it out. Just add e.g. `proj.fill = alpha("grey", 0.2)` to a `geom_magnify` call.

Warning: at present, using a `ragg` device on my machine (including the ragg RStudio backend) this causes a segfault. See https://github.com/r-lib/ragg/issues/156. It seems to work OK with quartz or cairo backends. I'm actively investigating this.

**Comment by hughjonesd** [comment]
This should now be in master and should no longer segfault.

**Comment by etiennebacher** [comment]
That's awesome, thanks!
