### ISSUE TITLE
Multiple insets in one plot

### ISSUE THREAD

**Issue by mfiorina** [hughjonesd/ggmagnify#2]
It would be great to be able to add multiple insets in the same plot. Currently, as the `ggmagnify()` function outputs a `GgMagnify` object, it cannot be re-entered into `ggmagnify()`.

Two possible (conceptual, I am not familiar with how the function works) options that you may have already considered?
- Allow `ggmagnify()` to take multiple lists of inputs, one for each inset
- Find a manner to allow `ggmagnify()` to accept a `GgMagnify` object as an input to which another inset can be added.

I have no idea how feasible either of these options are. But hopeful this could work as it would be a cool addition!

**Comment by hughjonesd** [comment]
This is an interesting point, hmm. 

The latest code (like right now) has a `compose()` function to turn a ggmagnify object back into a ggplot. But then calling ggmagnify a second time seems to do unhappy things....

**Comment by mfiorina** [comment]
I ended up going with a very messy method:
- Creating each inset I want using `ggmagnify`
- Creating a list with the original plot and all of the insets
- Modifying your `print.GgMagnify` function to loop over insets and add them to the original plot.

This worked, which is great! But not sure how much insight it provides into making `ggmagnify` work with a `GgMagnify` object as an input, although I'm glad that the `compose` function exists now. Might try it out.

**Comment by hughjonesd** [comment]
So here's a way to do this. You'll need the very latest commit.

```r
ggp <- ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) + geom_point()
ggm1 <- ggmagnify(ggp2, 
                  xlim = c(3.5, 3.7), ylim = c(5, 5.2),
                  inset_xlim = c(4, 4.4), inset_ylim = c(7, 8)) 

ggm2 <- ggmagnify(ggp, 
                  xlim = c(3, 3.5), ylim = c(6.5, 7.5),
                  inset_xlim = c(2.2, 3.2), inset_ylim = c(4.2, 6.2))
ggp2 <- compose( ggm1, ggp)
ggp2 <- compose( ggm2, ggp2)
ggp2
```

Please tell me if this works for you. It might be that your approach is better, though it requires having lists of all the components.

**Comment by hughjonesd** [comment]
See the README for a new example. Thanks for this idea.

**Comment by mfiorina** [comment]
Worked a charm! Thank you for putting this together so quickly!
