### ISSUE TITLE
ggmagnify appears to magnify more than just the polygon in maps

### ISSUE THREAD

**Issue by EdwardMoore13** [hughjonesd/ggmagnify#20]
I am trying to magnify just a small area of the UK (local authority) but using the ggmagnify it copies over areas outside the polygon. Whilst in the readme example with Texas it only had the Texas polygon. 

![map_issue](https://github.com/hughjonesd/ggmagnify/assets/130755930/7051c478-a694-4f19-87e0-80016981d22c)

I recreated the Texas example in your readme and the same thing happened. 

My code:

map + geom_magnify(aes(from = LAD22NM == "Powys"),
               to = c(0, 2, 54, 56), 
               shadow = TRUE, linewidth = 1, colour = "orange2",
               shape = "outline", 
               aspect = "fixed", 
               expand = 0)

**Comment by hughjonesd** [comment]
What graphics device are you using? Does it have the required capabilities?

**Comment by hughjonesd** [comment]
Closing. Feel free to reopen if you have more information.
