### ISSUE TITLE
Ggmagnify "axes = false" not working with complex plot theme()

### ISSUE THREAD

**Issue by jonathonkuntz** [hughjonesd/ggmagnify#3]
When using complex theme() in original ggplot, ggmagnify()'s "axes = FALSE" does not work.

`ggplot(data = dat, aes(x=x, y=y, color = z)) + 
theme(axis.text.x = element_text(angle = 315, hjust = 0, vjust = 1, size = 8), axis.text.y = element_text(size = 8), axis.title.x = element_text(size = 9), axis.title.y = element_text(size = 9, vjust = 2.5))`

**Comment by hughjonesd** [comment]
Should be fixed in master. Thanks. Don't forget to make examples self-contained and reproducible!
