### ISSUE TITLE
ggmagnify can magnify irregular areas

### ISSUE THREAD

**Issue by chuiqin** [hughjonesd/ggmagnify#4]
Thanks for developing such a great tool. I found out that ggmagnify can only magnify the graph in regular areas. But in the visualization of single-cell transcriptome sequencing, people are more inclined to zoom in on a specific cell subpopulation. However, the shape of cell subpopulations is irregular. Some R packages ggunchull and ggforce have advantages in drawing irregular graphics, but they cannot magnify the graphics and are not as beautiful and natural as ggmagnify. Looking forward to the new version of ggmagnify that can magnify irregular areas. I will continue to follow your work! Thank you very much!

**Comment by hughjonesd** [comment]
I know it would be cool... but this is just a one-day hack! I would bug @thomasp85
to create a ggmagnify-style geom in ggforce. Then you'd also get facetting etc.

**Comment by hughjonesd** [comment]
You can hack this yourself with a bit of work:

```r
dat <- data.frame(x = rnorm(100), y= rnorm(100), z = sample(5,100,replace=T))
ggp <- ggplot(dat, aes(x, y, color = z)) + geom_point() + xlim(-2,2) + ylim(-2,2)
ggp
v <- viewport(x = .3, y = .3, width = .35, height = .35, mask=circleGrob(gp=gpar(fill=rgb(0,0,0,1))))
pushViewport(v)
ggm <- ggmagnify(ggp, xlim = 0:1, ylim = 0:1, inset_xlim = c(-2, 0), inset_ylim = c(-2,0))
grid.draw(ggplotGrob(ggm$inset))
grid.draw(circleGrob(gp = gpar(color="black", fill = NA)))
```

Zoom and target lines are left as an exercise :-)

**Comment by chuiqin** [comment]
> You can hack this yourself with a bit of work:你可以通过一些工作自己破解这个：
> 
> ```r
> dat <- data.frame(x = rnorm(100), y= rnorm(100), z = sample(5,100,replace=T))
> ggp <- ggplot(dat, aes(x, y, color = z)) + geom_point() + xlim(-2,2) + ylim(-2,2)
> ggp
> v <- viewport(x = .3, y = .3, width = .35, height = .35, mask=circleGrob(gp=gpar(fill=rgb(0,0,0,1))))
> pushViewport(v)
> ggm <- ggmagnify(ggp, xlim = 0:1, ylim = 0:1, inset_xlim = c(-2, 0), inset_ylim = c(-2,0))
> grid.draw(ggplotGrob(ggm$inset))
> grid.draw(circleGrob(gp = gpar(color="black", fill = NA)))
> ```
> 
> Zoom and target lines are left as an exercise :-)缩放和目标线留作练习:-)

Thank you for your prompt reply. After I ran your sample code, I realized that you may have misunderstood me because of my vague description. In this sample code, `ggm <- ggmagnify(ggp, xlim = 0:1, ylim = 0:1, inset_xlim = c(-2, 0), inset_ylim = c(-2,0))`, it still It is a regular area that zooms in on the x-axis 0 to 1 and the y-axis 0 to 1. For your convenience, I drew a sketch by hand, I hope you don't mind it.

![image](https://user-images.githubusercontent.com/65839548/235103478-f67a350c-1942-4ea8-8757-13e57f8c5f0c.png)

**Comment by hughjonesd** [comment]
I understand. I think honestly, a really regular area, you had better do manually. The simplest thing would just be to copy the closest rectangle, set target and inset = FALSE, and draw the outlines manually.

**Comment by chuiqin** [comment]
Thank you for your reply! I combined the R packages `ggunchull` and `ggmagnify` in a clever way to draw irregular region graphics. I use the R package ggunchull to draw irregular curves. I use the R package ggmagnify to create a magnification effect. I set the two numbers in the parameters `xlim` and `ylim` in the `ggmagnify` function close enough so that the magnification effect looks like it starts from one point. But when I want to replace the image in `ggm$inset` with a brand new ggpolot2 object, I encounter failure. In the top right box, the brand new ggplot2 object is a grey. I wonder, if ggmagnify can support ggplot2 objects with `ggm$inset` set to either. This ggplot2 object can maintain its original appearance without being partially enlarged. If possible, the ggmagnify package can be used to display the results of re-clustering certain cell subpopulations in single-cell transcriptome data. I thought it would be a cool thing. Looking forward to your reply!
![image](https://user-images.githubusercontent.com/65839548/235286124-f6dd321a-50d4-4c39-abf7-47ef0701de76.png)

**Comment by hughjonesd** [comment]
I guess my feeling is, if you want to put something entirely new in the inset, then ggmagnify is not the right solution - have you tried [cowplot](https://wilkelab.org/cowplot/articles/drawing_with_on_plots.html)?

**Comment by hughjonesd** [comment]
OK, you got your wish!

Please try out:

```r
remotes::install_github(c("hughjonesd/ggmagnify@experiment-arbitrary-mask"
```

You should then be able to magnify an arbitrary area by passing in a grid grob.

The border lines aren't working perfectly yet.

**Comment by hughjonesd** [comment]
If you have a good example of using this in a scientific plot, and you can share it, that would be great for the README!
