### ISSUE TITLE
magnify linewidths and other aestetics

### ISSUE THREAD

**Issue by simonheb** [hughjonesd/ggmagnify#6]
I'm magnifying a section of a ggraph object. It works ok, but the linewidths do not get magnified, which looks odd.

Is there a way to magnify aesthetics too?

**Comment by hughjonesd** [comment]
Edit `ggm$inset`. See the advanced example in the README.

**Comment by simonheb** [comment]
Thanks a lot. Great package btw.

Beste Grüße,

Simon Heß
