### ISSUE TITLE
object 'dv' not found

### ISSUE THREAD

**Issue by Syutenjyo** [hughjonesd/ggmagnify#9]
hello, i have just met a problem when i use
```
ggp <- ggplot(dv, aes(Position, NegLogP, color = cut)) + 
  geom_point(color = "darkblue", alpha = 0.8, size = 0.8) +
  labs(title = "GWAS p-values for cognitive function",
       subtitle = "Davies et al. (2018).", y = "-log(p)")
```
it says "object 'dv' not found".
how can i get the `dv` variant?

**Comment by hughjonesd** [comment]
It comes from the data I was using, see the source at the bottom of the article. I think it's publicly available, but only for research purposes.

**Comment by hughjonesd** [comment]
Also, no offence, but github issues are for bug reports, not for help requests. If you need help, try stackoverflow.

**Comment by Syutenjyo** [comment]
Thank you for your answer. I am a beginner in computer science and I will pay attention to these issues in the future.
